Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: consistent_comma

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 16

Style/SignalException:
  EnforcedStyle: semantic

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - 'spec/**/*'

Style/SignalException:
  EnforcedStyle: semantic

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent
